### ISSUE TITLE
Feature request: Upload haddocks

### ISSUE THREAD

**Issue by maralorn** [domenkozar/releaser#10]
Hey, would it be an option to add an generate and upload haddocks step to releaser or is that step left out on purpose?

**Comment by domenkozar** [comment]
I rely on haddocks being generated by hackage, but I'm not opposed to a PR that adds haddock generation.

**Comment by maralorn** [comment]
Uh, I didn‘t even know that was a thing. But perhaps someone (maybe I) will come around to implement this nonetheless.

**Comment by kutyel** [comment]
We'd like to work on this! We have to run `cabal v2-haddock --builddir="dist-newstyle" --haddock-for-hackage --enable-doc` EVERY SINGLE TIME and I'd love to automate it haha 😂

**Comment by maralorn** [comment]
I think I want to give a shot at implementing this feature.

@kutyel I have two questions:

1. Why do you specify `--builddir="dist-newstyle"`? In my cabal that‘s the default.
2. Why do you specify `--enable-doc`? For me generating the haddocks for hackage works without that parameter. What‘s the difference?

**Comment by kutyel** [comment]
I'll try without those but we were using the latest version of haddock and apparently and if I remember correctly without them the doc generation wasn't correct or working, thanks for the PR! 🙌

**Comment by domenkozar** [comment]
It currently fails with 

```
>> Running $ cabal haddock
>> Looking for a cabal file in .
>> Found releaser-0.3.0.0
Warning: The package list for 'hackage.haskell.org' is 153 days old.
Run 'cabal update' to get the latest list of available packages.
cabal: Failed to build pretty-terminal-0.1.0.0 (which is required by
releaser-0.3.0.0). See the build log above for details.
Failed to build regex-base-0.94.0.0 (which is required by releaser-0.3.0.0).
See the build log above for details.

releaser: readCreateProcess: cabal "v2-haddock" "--haddock-for-hackage" (exit 1): failed
```

So that would be good to fix - to allow the release to continue.

**Comment by maralorn** [comment]
Okay.

1. This is the last step in the release process so when it fails everything else should have worked as before.
2. I fear this is a problem with the project being a stack project and not a cabal project. I am not sure what we can do about it. It would be desirable to find a solution that works both for cabal and for stack, ideally without discovering what type of project it is manually. I don‘t use stack in my projects. This is also an indication that this might fail in other circumstances, too. e.g. when you build your project with nix and don‘t run releaser in the nix-shell.

**Comment by maralorn** [comment]
btw. sadly the [docs for releaser couldn‘t get built on hackage](
https://hackage.haskell.org/package/releaser-0.3.0.0/reports/2) because it tries to use the wrong Cabal dependency version to build it.
